### ISSUE TITLE
Installing the dev version on mac osx

### ISSUE THREAD

**Issue by hanhanhankim** [gilestrolab/pySolo#15]
Hi,
I am trying to run the development version of pySolo on a Mac OSX. All the packages necessary for supporting pySolo are properly installed. However, I consistently seem to have an issue related to wxPython:
<img width="576" alt="screen shot 2017-03-16 at 9 45 57 pm" src="https://cloud.githubusercontent.com/assets/26473149/24025665/2cd37898-0a92-11e7-8d41-a8b976454af7.png">
How would I go about resolving this problem? Thank you.

**Comment by ggilestro** [comment]
Hi, can you find out what version of wxPython you are running?


--
Giorgio F. Gilestro
http://gilest.ro

**Comment by hanhanhankim** [comment]
Hi,
I downloaded wxPython3.0-osx-cocoa-py2.7 from https://wxpython.org/download.php. It is one of the MacOSX binaries. Thank you for your help.

**Comment by ggilestro** [comment]
There is a file in the dev version called `check_components.py`
Can you please run that one and paste its output here?

**Comment by hanhanhankim** [comment]
Hi,
Yes, here is the output:
<img width="639" alt="screen shot 2017-03-18 at 8 49 12 pm" src="https://cloud.githubusercontent.com/assets/26473149/24077202/6396eb54-0c1c-11e7-8baf-3607a8b8792d.png">
Thanks again for your help.

**Comment by ggilestro** [comment]
So, the problem is that you are using the "Phoenix" version of wxPythom which is not supported. You will have to replace it with the classic version (3.0.2). I believe the file you need can be found here https://sourceforge.net/projects/wxpython/files/wxPython/3.0.2.0/wxPython3.0-osx-3.0.2.0-cocoa-py2.7.dmg

**Comment by hanhanhankim** [comment]
Thank you! It all works fine and well now. I am going to post on here the Mac OSX-friendly wxPython download link I used, in case others also run into this problem:
https://wxpython.org/snapshots/

**Comment by ggilestro** [comment]
Thanks!

**Comment by Eyshika** [comment]
How can wxpython classic version be downloaded in a virtualenvironment ?

**Comment by ggilestro** [comment]
> How can wxpython classic version be downloaded in a virtualenvironment ? @ggilestro

I have not tested this and I have never used Mac so I may be very wrong about this but if you use anaconda it should be something like:

```
#create a new environment
conda env create -n pysolo

#activate the environment
conda activate pysolo

#install this or other deps
conda install wxpython=3.0.2.0

```

Something similar can also be done with `pip`.
